config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'
  
  ActiveAdmin.routes(self)

  resources :pictures

  post 'pictures/:id' => 'pictures#create_comment', as: 'create_comment'

  devise_for :users

end

app/models/adapters/only_admins.rb
class Adapters::OnlyAdmins < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject = nil)
    user.admin?
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :picture
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :name, presence: true, length: {maximum: 50}
  has_many :pictures
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

  def access_denied(exception)
    flash[:danger] = exception.message
    redirect_to root_url
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.order(created_at: :desc)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = current_user.pictures.build(picture_params)

    if @picture.save
      redirect_to @picture
    else
      render 'new'
    end
  end

  def edit
    @picture = Picture.find(params[:id])
  end

  def update
    @picture = Picture.find(params[:id])

    if @picture.update(picture_params)
      redirect_to @picture
    else
      render 'edit'
    end
  end

  def show
    @picture = Picture.find(params[:id])
    @comment = Comment.new
    @comments = Comment.all
  end

  def create_comment
    @comment = current_user.comments.build(comment_params)
    if @comment.save
      redirect_to root_path
    end
  end

  def destroy
    Picture.destroy(params[:id])

    redirect_to user_path
  end

  private

  def picture_params
    params.require(:picture).permit(:name, :user_id, :image)
  end

  def comment_params
    params.require(:comment).permit(:note, :rate, :user_id, :picture_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/application/navbar' %>

<div class="container">

  <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: "alert alert-#{type}" %>
  <% end %>

  <%= yield %>

</div>
</body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Shop', root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!-- Pages links -->
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
            <p class="navbar-text">
              Logged in as <%= current_user.name %>
            </p>
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <% if current_user.admin? %>
                      <li><%= link_to 'Admin Panel', admin_root_path %></li>
                  <% end %>

                  <li><%= link_to 'Edit profile', edit_user_registration_path(current_user) %></li>
                  <li><a href="#">View orders</a></li>
                  <li class="divider"></li>
                  <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
                </ul>
              </li>
            </ul>
        <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-default navbar-btn' %>
            <%= link_to 'Log in', new_user_session_path, class: 'btn btn-default navbar-btn' %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/pictures/_form.html.erb
<%= form_for @picture, html: {class: 'form-horizontal'} do |f| %>

    <div class="form-group <%= 'has-error' if @picture.errors[:title].any? %>">
      <div class="col-sm-10">
        <%= f.label :name %>
        <%= f.text_field :name %> <br/>
      </div>
    </div>

    <%= f.label :image %>
    <%= f.file_field :image %> <br/>

    <%= f.submit %>

<% end %>

app/views/pictures/edit.html.erb
<h1>Edit picture</h1>

<%= render 'form' %>

app/views/pictures/index.html.erb
<h1>Welcome to Gallery!</h1>


<% @pictures.each do |picture| %>
<div>

      <%= link_to picture.name, picture_path(picture.id) %> <br/>
      <%= image_tag picture.image.url(:medium) %> <br/>
      <%= picture.user.name %>



</div>


<% end %>

<% if user_signed_in? %>
<%= link_to 'create', new_picture_path, class: 'btn btn-primary' %>
<% end %>

app/views/pictures/new.html.erb
<h1>Add new picture</h1>

<% if user_signed_in? %>
    <%= render 'form' %>
<% else %>
    <h2>You should sign in before adding pictures</h2>
<% end %>

app/views/pictures/show.html.erb
<h1>This is <%= @picture.name %></h1>

<%= image_tag @picture.image.url(:medium) %>

<% if user_signed_in? %>
    <%= form_for @comment, :url => { :action => 'create_comment', html: {class: 'form-horizontal'} } do |f| %>
        <%= f.hidden_field :picture_id, :value => @picture.id %>
        <%= f.label :note %>
        <%= f.text_area :note %> <br/>

        <%= f.label :rate %>
        <%= f.select :rate, (1..5) %> <br/>

       <%= f.submit class: 'btn btn-primary' %>
    <% end %>
<% end %>

<hr/>
<hr/>

<% @comments.each do |comment| %>
    <% if comment.picture_id == @picture.id %>

        <div class="panel panel-default">
          <div class="panel-heading"> by: <%= comment.user.name %> <br/> score: <%= comment.rate %></div>
          <div class="panel-body">
            <%= comment.note %>
          </div>
        </div>
    <% end %>
<% end %>